//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsFactory.Sqlite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expenses
    {
        public long Id { get; set; }
        public Nullable<long> ShopId { get; set; }
        public Nullable<double> SalaryExpenses { get; set; }
        public Nullable<double> RentExpenses { get; set; }
    }
}
